filetype plugin indent on


set smartindent 
set nu
set laststatus=2
set noswapfile          "No crea los .swp
set title
set hlsearch            "Ilumina las palabras que estoy buscando con *
set incsearch           "Ilumina las palabras que estoy buscando con /
set encoding=utf-8
set fileformat=unix
set cursorline
set autochdir   "Te pone en el directorio del fichero
source ~/.vim/vundle.vim
filetype on
filetype plugin on

au BufRead,BufNewFile *.html.twig set filetype=html

" Configuración específica para archivos de JavaScript, HTML, CSS
autocmd FileType javascript,css setlocal tabstop=2 shiftwidth=2

autocmd FileType html setlocal tabstop=2 shiftwidth=2 expandtab

" " Configuración específica para archivos de Python
autocmd FileType python setlocal tabstop=4 shiftwidth=4
"
" " Configuración específica para archivos de C y C++
autocmd FileType c,cpp setlocal tabstop=4 shiftwidth=4
"
" " Configuración específica para archivos de Ruby
autocmd FileType ruby setlocal tabstop=2 shiftwidth=2
"
" " Configuración específica para archivos de Go (sin expandtab)
autocmd FileType go setlocal tabstop=4 shiftwidth=4 noexpandtab
"
" " Configuración específica para archivos de PHP
autocmd FileType php setlocal tabstop=4 shiftwidth=4

set pastetoggle=<F2>


map <F3> :call gitblame#echo()<CR>
map <F4> :echo gitbranch#name()<CR>
map <F7> :NERDTreeToggle<CR>
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
map <F8> :TagbarToggle<CR>
let g:lightline = {
	\ 'colorscheme': 'wombat',
\ }
syntax on
source ~/.vim/colors/dracula.vim

"Abrir vim en la línea que estaba
if has("autocmd")
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
if !has('gui_running')
set t_Co=256
endif
