set nu
set laststatus=2
set noswapfile          "No crea los .swp
set title
set hlsearch            "Ilumina las palabras que estoy buscando con *
set incsearch           "Ilumina las palabras que estoy buscando con /
set encoding=utf-8
set fileformat=unix
set cursorline
set autochdir   "Te pone en el directorio del fichero
source ~/.vim/vundle.vim
filetype on
filetype plugin on

"set tabstop=4     " Size of a hard tabstop (ts).
"set shiftwidth=4  " Size of an indentation (sw).
set noexpandtab   " Always uses tabs instead of space characters (noet).
set autoindent    " Copy indent from current line when starting a new line (ai).

map <F2> :GitGutterLineHighlightsToggle<CR>
map <F3> :call gitblame#echo()<CR>
map <F4> :echo gitbranch#name()<CR>
map <F7> :NERDTreeToggle<CR>
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
map <F8> :TagbarToggle<CR>
let g:lightline = {
	\ 'colorscheme': 'wombat',
\ }
syntax on
source ~/.vim/colors/dracula.vim

"Abrir vim en la línea que estaba
if has("autocmd")
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
if !has('gui_running')
set t_Co=256
endif
