set nu
set laststatus=2
set noswapfile		"No crea los .swp
set title
set hlsearch		"Ilumina las palabras que estoy buscando con *
set incsearch		"Ilumina las palabras que estoy buscando con /
set encoding=utf-8
set cursorline
set autochdir	"Te pone en el directorio del fichero
source ~/.vim/vundle.vim
filetype on
filetype plugin on

set tabstop=4     " Size of a hard tabstop (ts).
set shiftwidth=4  " Size of an indentation (sw).
set noexpandtab   " Always uses tabs instead of space characters (noet).
set autoindent    " Copy indent from current line when starting a new line (ai).

map <F2> :GitGutterLineHighlightsToggle<CR>
map <F3> :call gitblame#echo()<CR>
"""""""""""""""""""""""""""""""""""""""""
"	    PALETA DE COLORES               "

source ~/.vim/colors/solarized.vim

	syntax enable
	set background=dark
	let g:solarized_termcolors=256
	colorscheme solarized

"										"
"""""""""""""""""""""""""""""""""""""""""
